# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'IntelligentBasket' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IntelligentBasket

pod 'Alamofire'
pod 'SnapKit'
pod "PromiseKit", "~> 6.8"
pod 'PromiseKit/Alamofire', '~> 6.0'
pod "PromiseKit/UIKit", "~> 6.0"
pod "PromiseKit/UIImagePickerController"
pod 'JGProgressHUD'
pod 'MMMaterialDesignSpinner'
pod 'BEMCheckBox'
pod 'LMJDropdownMenu'

end
